services:
  - type: web
    name: blog-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn index:app"
    envVars:
      - key: FLASK_ENV
        value: production
