"""Updating time-read

Revision ID: 7102f2c8aaf9
Revises: 42b777133ab0
Create Date: 2025-07-17 20:40:18.397306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7102f2c8aaf9'
down_revision = '42b777133ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_time', sa.Integer(), nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable='False')
        batch_op.alter_column('blog_id',
               existing_type=sa.INTEGER(),
               nullable='False')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('blog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('read_time')

    # ### end Alembic commands ###
